package packs

// Georgia source pack — verified 2026-08-01 via web search.
// Government: GA marriage records held by county Probate Court.
// Church: 2 Catholic dioceses (Atlanta, Savannah).

var gaPack = StatePack{
	State: "GA",
	Cities: []CityDef{
		{ID: "city_atlanta_ga", State: "GA", County: "13121", Name: "Atlanta",
			Lat: 33.7490, Lng: -84.3880, Markets: []string{"atlanta", "atl", "ga", "fulton", "metroatlanta"}},
		{ID: "city_savannah_ga", State: "GA", County: "13051", Name: "Savannah",
			Lat: 32.0809, Lng: -81.0912, Markets: []string{"savannah", "coastalga", "chatham"}},
	},
	Government: []GovSource{
		{CountyFIPS: "13121", CourtName: "Fulton County Probate Court",
			CourtURL:  "https://www.fultonprobatega.org/195/Marriage-Licenses",
			SearchURL: "https://www.fultonprobatega.org/195/Marriage-Licenses",
			Note:      "Marriage record request by mail/in-person; no online search portal."},
		{CountyFIPS: "13135", CourtName: "Gwinnett County Probate Court",
			CourtURL:  "https://gwinnettcountycourt.org",
			SearchURL: "https://gwinnettcountycourt.org/marriage-divorce-records/",
			Note:      "Marriage records via Probate Court; VitalChek for electronic requests, no direct online search."},
		{CountyFIPS: "13067", CourtName: "Cobb County Probate Court",
			CourtURL:  "https://www.cobbcounty.org/courts/probate",
			SearchURL: "https://www.cobbcounty.org/courts/probate",
			Note:      "Marriage records via Probate Court; request-oriented."},
		{CountyFIPS: "13089", CourtName: "DeKalb County Probate Court",
			CourtURL:  "https://dekalbcountyga-web.tylerhost.net/web/user/disclaimer",
			SearchURL: "https://dekalbcountyga-web.tylerhost.net/web/user/disclaimer",
			Note:      "Marriage records via Probate Court; request-oriented."},
		{CountyFIPS: "13051", CourtName: "Chatham County Probate Court",
			CourtURL:  "https://www.chathamcountyga.gov/government/courts/probate-court",
			SearchURL: "https://www.chathamcountyga.gov/government/courts/probate-court",
			Note:      "Marriage records via Probate Court; request-oriented."},
		{CountyFIPS: "13245", CourtName: "Richmond County Probate Court",
			CourtURL:  "https://www.augustaga.gov",
			SearchURL: "https://www.augustaga.gov",
			Note:      "Marriage records via Probate Court; request-oriented."},
		{CountyFIPS: "13063", CourtName: "Clayton County Probate Court",
			CourtURL:  "https://www.claytoncountyga.gov",
			SearchURL: "https://www.claytoncountyga.gov",
			Note:      "Marriage records via Probate Court; request-oriented."},
		{CountyFIPS: "13077", CourtName: "Columbia County Probate Court",
			CourtURL:  "https://columbiacountyga.gov/",
			SearchURL: "https://www.georgiaprobaterecords.com/Marriage/SearchMarriages.aspx",
			Note:      "Georgia statewide probate marriage records search; search by county, name, and date range."},
		{CountyFIPS: "13215", CourtName: "Muscogee County Probate Court",
			CourtURL:  "https://columbusga.gov/",
			SearchURL: "https://www.georgiaprobaterecords.com/Marriage/SearchMarriages.aspx",
			Note:      "Georgia statewide probate marriage records search; search by county, name, and date range."},
		{CountyFIPS: "13045", CourtName: "Cherokee County Probate Court",
			CourtURL:  "https://www.cherokeecountyga.gov/",
			SearchURL: "https://www.georgiaprobaterecords.com/Marriage/SearchMarriages.aspx",
			Note:      "Georgia statewide probate marriage records search; search by county, name, and date range."},
	},
	Dioceses: []DioceseDef{
		{Slug: "atlanta", Name: "Archdiocese of Atlanta", Type: "archdiocese",
			Website: "https://archatl.com", Directory: "https://archatl.com/parish-finder", HubCityID: "city_atlanta_ga"},
		{Slug: "savannah", Name: "Diocese of Savannah", Type: "diocese",
			Website: "https://diosav.org", Directory: "https://diosav.org/parishes", HubCityID: "city_savannah_ga"},
	},
	Parishes: []ParishDef{
		{DioceseSlug: "atlanta", Name: "Cathedral of Christ the King", Address: "2699 Peachtree Rd NE, Atlanta, GA 30305"},
		{DioceseSlug: "atlanta", Name: "St. Philip Catholic Church", Address: "2401 W Peachtree St NW, Atlanta, GA 30309"},
		{DioceseSlug: "atlanta", Name: "Holy Spirit Catholic Church", Address: "4465 Northside Dr NW, Atlanta, GA 30327"},
		{DioceseSlug: "atlanta", Name: "St. Ann Catholic Church", Address: "4905 Roswell Rd, Marietta, GA 30062"},
		{DioceseSlug: "atlanta", Name: "Transfiguration Catholic Church", Address: "1811 Blackwell Rd NW, Marietta, GA 30066"},
	},
	Vendors: []VendorDef{
		{Name: "Hazel Wedding Studio", OfficialURL: "https://www.hazelweddingstudio.com/",
			Handle: "hazelweddingstudio", SourceClass: "engagement_photographer",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-01"},
		{Name: "Meli & Chris Photography", OfficialURL: "https://atlweddingphotos.com/",
			Handle: "meliandchris", SourceClass: "engagement_photographer",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-01"},
		{Name: "J Estill Photography", OfficialURL: "https://jestillphotography.com/",
			Handle: "jestillphotography", SourceClass: "engagement_photographer",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-01"},
		{Name: "Mandi Mitchell Photography", OfficialURL: "https://mandimitchell.com/",
			Handle: "mandimitchell", SourceClass: "engagement_photographer",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-01"},
		{Name: "Ambient+Studio", OfficialURL: "https://www.ambientplusstudio.com/",
			Handle: "ambientplusstudio", SourceClass: "wedding_venue",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-01"},
		// Atlanta wedding planners
		{Name: "Event Productions by Gen", OfficialURL: "https://eventproductionsbygen.com/",
			Handle: "eventproductionsbygen", SourceClass: "wedding_planner",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-01"},
		{Name: "Kesha Nettles Events", OfficialURL: "https://keshanettlesevents.com/",
			Handle: "keshanettlesevents", SourceClass: "wedding_planner",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-01"},
		{
			Name: "Denis Reggie Photographers", OfficialURL: "https://www.denisreggie.com/",
			Handle: "denisreggie", SourceClass: "engagement_photographer",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-03",
		},
		{
			Name: "Emily Nicole Photography", OfficialURL: "https://emilynicolephotography.com/",
			Handle: "emilynicole_photos", SourceClass: "engagement_photographer",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-03",
		},
		{
			Name: "Unique Floral Expressions", OfficialURL: "https://uniquefloralexpressions.com/",
			Handle: "ufebuckhead", SourceClass: "florist",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-03",
		},
		{
			Name: "Flux Floral Design", OfficialURL: "https://www.fluxfloral.com/",
			Handle: "fluxfloral", SourceClass: "florist",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-03",
		},
		{
			Name: "Flowers by Yona", OfficialURL: "https://flowersbyyona.com/",
			Handle: "flowersbyyona", SourceClass: "florist",
			CityID: "city_atlanta_ga", State: "GA", City: "Atlanta", Verified: "2026-08-03",
		},
		{
			Name: "Esther Griffin Photography", OfficialURL: "https://esthergriffinphotography.com/",
			Handle: "esthergriffinphoto", SourceClass: "engagement_photographer",
			CityID: "city_savannah_ga", State: "GA", City: "Savannah", Verified: "2026-08-03",
		},
		{
			Name: "Plant Riverside District", OfficialURL: "https://www.plantriverside.com/",
			Handle: "plantriversidedistrict", SourceClass: "wedding_venue",
			CityID: "city_savannah_ga", State: "GA", City: "Savannah", Verified: "2026-08-03",
		},
	},
}
