package packs

// Pennsylvania source pack — verified 2026-08-01 via web search.
// Government: PA marriage records held by county Orphans' Court / Register of Wills.
// Philadelphia has an online marriage license search; Allegheny has online search post-1996.

var paPack = StatePack{
	State: "PA",
	Cities: []CityDef{
		{ID: "city_philadelphia_pa", State: "PA", County: "42101", Name: "Philadelphia",
			Lat: 39.9526, Lng: -75.1652, Markets: []string{"philadelphia", "philly", "pa", "delawarevalley"}},
		{ID: "city_pittsburgh_pa", State: "PA", County: "42003", Name: "Pittsburgh",
			Lat: 40.4406, Lng: -79.9959, Markets: []string{"pittsburgh", "pgh", "allegheny", "westernpa"}},
	},
	Government: []GovSource{
		{CountyFIPS: "42101", CourtName: "Philadelphia Register of Wills",
			CourtURL:  "https://www.phila.gov/departments/register-of-wills/",
			SearchURL: "https://www.phila.gov/departments/register-of-wills/marriage-license-search/",
			Note:      "Online marriage license search for records from 1995+; enumeration candidate."},
		{CountyFIPS: "42003", CourtName: "Allegheny County Department of Court Records",
			CourtURL:  "https://www.alleghenycounty.us/Government/Records/Marriage-Records",
			SearchURL: "https://www.alleghenycounty.us/Government/Records/Marriage-Records",
			Note:      "Online marriage license search for records from 1996+; pre-1996 by mail request."},
		{CountyFIPS: "42091", CourtName: "Montgomery County Register of Wills",
			CourtURL:  "https://www.montgomerycountypa.gov/202/Register-of-Wills",
			SearchURL: "https://www.montgomerycountypa.gov/204/Obtaining-a-Marriage-Record",
			Note:      "Marriage records from 1885; in-person or mail request, no online search."},
		{CountyFIPS: "42017", CourtName: "Bucks County Register of Wills",
			CourtURL:  "https://www.buckscounty.gov/government/RowOfficers/RegisterofWills",
			SearchURL: "https://www.buckscounty.gov/government/RowOfficers/RegisterofWills",
			Note:      "Marriage records via Orphans' Court; request-oriented, no online search."},
		{CountyFIPS: "42045", CourtName: "Delaware County Register of Wills",
			CourtURL:  "https://www.delcopa.gov/registerofwills",
			SearchURL: "https://www.delcopa.gov/registerofwills",
			Note:      "Marriage records via Orphans' Court; request-oriented."},
		{CountyFIPS: "42029", CourtName: "Chester County Register of Wills",
			CourtURL:  "https://www.chesco.org/156/Register-of-Wills",
			SearchURL: "https://www.chesco.org/156/Register-of-Wills",
			Note:      "Marriage records via Orphans' Court; request-oriented."},
		{CountyFIPS: "42071", CourtName: "Lancaster County Register of Wills",
			CourtURL:  "https://www.co.lancaster.pa.us",
			SearchURL: "https://www.co.lancaster.pa.us",
			Note:      "Marriage records via Orphans' Court; request-oriented."},
		{CountyFIPS: "42011", CourtName: "Berks County Register of Wills",
			CourtURL:  "https://www.berkspa.gov/",
			SearchURL: "http://rwills.co.berks.pa.us/geneology/Marriages.aspx",
			Note:      "Online marriage license search by name; covers historical marriage records with volume and page search."},
		{CountyFIPS: "42049", CourtName: "Erie County Clerk of Records / Register of Wills",
			CourtURL:  "https://courts.eriecountypa.gov/",
			SearchURL: "",
			Note:      "No online marriage record search; marriage applications via CourtPro. Records require in-person or mail request."},
		{CountyFIPS: "42013", CourtName: "Blair County Clerk of Orphans' Court",
			CourtURL:  "https://www.blaircountypa.gov/",
			SearchURL: "",
			Note:      "No online marriage record search; applications submitted online but records require in-person or mail request."},
	},
	Dioceses: []DioceseDef{
		{Slug: "philadelphia", Name: "Archdiocese of Philadelphia", Type: "archdiocese",
			Website: "https://archphila.org", Directory: "https://archphila.org/parish/", HubCityID: "city_philadelphia_pa"},
		{Slug: "pittsburgh", Name: "Diocese of Pittsburgh", Type: "diocese",
			Website: "https://diopitt.org", Directory: "https://diopitt.org/alphabetical-list-of-current-parishes", HubCityID: "city_pittsburgh_pa"},
		{Slug: "allentown", Name: "Diocese of Allentown", Type: "diocese",
			Website: "https://www.allentowndiocese.org", Directory: "https://www.allentowndiocese.org/parishes"},
		{Slug: "harrisburg", Name: "Diocese of Harrisburg", Type: "diocese",
			Website: "https://www.hbgdiocese.org", Directory: "https://www.hbgdiocese.org/parishes"},
		{Slug: "scranton", Name: "Diocese of Scranton", Type: "diocese",
			Website: "https://www.dioceseofscranton.org", Directory: "https://www.dioceseofscranton.org/find-a-parish/"},
		{Slug: "erie", Name: "Diocese of Erie", Type: "diocese",
			Website: "https://www.eriercd.org", Directory: "https://www.eriercd.org/parish-directory.html"},
		{Slug: "greensburg", Name: "Diocese of Greensburg", Type: "diocese",
			Website: "https://www.dioceseofgreensburg.org", Directory: "https://www.dioceseofgreensburg.org/parishes"},
		{Slug: "altoona_johnstown", Name: "Diocese of Altoona-Johnstown", Type: "diocese",
			Website: "https://www.ajdiocese.org", Directory: "https://www.ajdiocese.org/parishes"},
	},
	Parishes: []ParishDef{
		{DioceseSlug: "philadelphia", Name: "Cathedral Basilica of Saints Peter and Paul",
			Address: "1723 Race St, Philadelphia, PA 19103"},
		{DioceseSlug: "philadelphia", Name: "St. Adalbert Church", Address: "2640 E Allegheny Ave, Philadelphia, PA 19134"},
		{DioceseSlug: "philadelphia", Name: "St. Barbara Church", Address: "5351 L St, Philadelphia, PA 19120"},
		{DioceseSlug: "philadelphia", Name: "St. Bartholomew Church", Address: "4700 Bromall Ave, Prospect Park, PA 19076"},
	},
	Vendors: []VendorDef{
		{Name: "J&J Studios Philadelphia", OfficialURL: "https://jjstudiosphiladelphia.com/",
			Handle: "jjstudiosphilly", SourceClass: "engagement_photographer",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		{Name: "Two17 Photo & Cinema", OfficialURL: "https://two17photo.com/",
			Handle: "two17photo", SourceClass: "engagement_photographer",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01",
			KnotURL: "https://www.theknot.com/marketplace/217-photography-dresher-pa-562220"},
		{Name: "Amber Dawn Photography", OfficialURL: "https://amber-dawn.com/",
			Handle: "amberdawnphoto", SourceClass: "engagement_photographer",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		{Name: "Eternally Yours Studio", OfficialURL: "https://eternallyyoursstudio.com/",
			Handle: "eternallyyoursstudio", SourceClass: "engagement_photographer",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		{Name: "Hoffer Photography", OfficialURL: "https://hofferphotography.com/",
			Handle: "hofferphotography", SourceClass: "engagement_photographer",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		// Philadelphia wedding planners
		{Name: "LaRue Events", OfficialURL: "https://larueevents.com/",
			Handle: "larueevents", SourceClass: "wedding_planner",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		{Name: "The Styled Bride", OfficialURL: "https://thestyledbride.com/",
			Handle: "styledbride", SourceClass: "wedding_planner",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		// Philadelphia/Pittsburgh florists
		{Name: "Robertson's Flowers", OfficialURL: "https://www.robertsonsflowers.com/",
			Handle: "robertsonsflowers", SourceClass: "florist",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		{Name: "Lowe & Wilde", OfficialURL: "https://www.loweandwilde.com/",
			Handle: "loweandwilde", SourceClass: "florist",
			CityID: "city_pittsburgh_pa", State: "PA", City: "Pittsburgh", Verified: "2026-08-01"},
		// Pennsylvania videographers
		{Name: "Philadelphia Wedding Films", OfficialURL: "https://www.phillyweddingfilms.com/",
			Handle: "phillyweddingfilms", SourceClass: "videographer",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		{Name: "Steel City Films", OfficialURL: "https://www.steelcityfilms.com/",
			Handle: "steelcityfilms", SourceClass: "videographer",
			CityID: "city_pittsburgh_pa", State: "PA", City: "Pittsburgh", Verified: "2026-08-01"},
		// Pennsylvania wedding cake bakeries
		{Name: "The Cake Stand", OfficialURL: "https://www.thecakestand.com/",
			Handle: "thecakestand", SourceClass: "wedding_cake",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		{Name: "Prantl's Bakery", OfficialURL: "https://www.prantlsbakery.com/",
			Handle: "prantlsbakery", SourceClass: "wedding_cake",
			CityID: "city_pittsburgh_pa", State: "PA", City: "Pittsburgh", Verified: "2026-08-01"},
		// Pennsylvania bridal shops
		{Name: "Anna Be Bridal", OfficialURL: "https://www.annabebridal.com/",
			Handle: "annabebridal", SourceClass: "bridal_shop",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		{Name: "Luxe Bridal Pittsburgh", OfficialURL: "https://www.luxebridalpgh.com/",
			Handle: "luxebridalpgh", SourceClass: "bridal_shop",
			CityID: "city_pittsburgh_pa", State: "PA", City: "Pittsburgh", Verified: "2026-08-01"},
		// Pennsylvania officiants
		{Name: "Philadelphia Wedding Officiants", OfficialURL: "https://www.phillyweddingofficiants.com/",
			Handle: "phillyweddingofficiants", SourceClass: "officiant",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-01"},
		{Name: "Pittsburgh Wedding Officiant", OfficialURL: "https://www.pghweddingofficiant.com/",
			Handle: "pghweddingofficiant", SourceClass: "officiant",
			CityID: "city_pittsburgh_pa", State: "PA", City: "Pittsburgh", Verified: "2026-08-01"},
		{
			Name: "McShea Photography", OfficialURL: "https://www.mcsheaphotography.com/",
			Handle: "mcsheaphotography", SourceClass: "engagement_photographer",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-03",
		},
		{
			Name: "Grace & Ardor Co", OfficialURL: "https://graceandardor.com/",
			Handle: "graceandardor", SourceClass: "engagement_photographer",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-03",
		},
		{
			Name: "Phipps Conservatory and Botanical Gardens", OfficialURL: "https://www.phipps.conservatory.org/",
			Handle: "phippsconservatory", SourceClass: "wedding_venue",
			CityID: "city_pittsburgh_pa", State: "PA", City: "Pittsburgh", Verified: "2026-08-03",
		},
		{
			Name: "Robertson's Flowers & Events", OfficialURL: "https://www.robertsonsweddings.com/",
			Handle: "robertsonsflowers", SourceClass: "florist",
			CityID: "city_philadelphia_pa", State: "PA", City: "Philadelphia", Verified: "2026-08-03",
		},
	},
}
