const CITIES: Record<string, { city: string; pop: string; tier: 1 | 2 | 3; signal: string }[]> = {
  AL: [
    { city: "Birmingham", pop: "197K", tier: 1, signal: "Active" },
    { city: "Huntsville", pop: "215K", tier: 1, signal: "Active" },
    { city: "Montgomery", pop: "200K", tier: 2, signal: "Pending" },
    { city: "Mobile", pop: "187K", tier: 2, signal: "Pending" },
    { city: "Tuscaloosa", pop: "101K", tier: 3, signal: "Idle" },
  ],
  AK: [
    { city: "Anchorage", pop: "291K", tier: 1, signal: "Active" },
    { city: "Fairbanks", pop: "32K", tier: 2, signal: "Idle" },
    { city: "Juneau", pop: "32K", tier: 3, signal: "Idle" },
  ],
  AZ: [
    { city: "Phoenix", pop: "1.6M", tier: 1, signal: "Active" },
    { city: "Tucson", pop: "542K", tier: 1, signal: "Active" },
    { city: "Scottsdale", pop: "241K", tier: 1, signal: "Active" },
    { city: "Mesa", pop: "504K", tier: 2, signal: "Pending" },
    { city: "Chandler", pop: "275K", tier: 2, signal: "Pending" },
    { city: "Tempe", pop: "195K", tier: 2, signal: "Pending" },
  ],
  AR: [
    { city: "Little Rock", pop: "203K", tier: 1, signal: "Active" },
    { city: "Fayetteville", pop: "95K", tier: 2, signal: "Pending" },
    { city: "Fort Smith", pop: "89K", tier: 3, signal: "Idle" },
  ],
  CA: [
    { city: "Los Angeles", pop: "3.9M", tier: 1, signal: "Active" },
    { city: "San Francisco", pop: "874K", tier: 1, signal: "Active" },
    { city: "San Diego", pop: "1.4M", tier: 1, signal: "Active" },
    { city: "San Jose", pop: "1.0M", tier: 1, signal: "Active" },
    { city: "Sacramento", pop: "525K", tier: 1, signal: "Active" },
    { city: "Irvine", pop: "307K", tier: 1, signal: "Active" },
    { city: "Oakland", pop: "433K", tier: 2, signal: "Pending" },
    { city: "Santa Barbara", pop: "88K", tier: 2, signal: "Pending" },
    { city: "Napa", pop: "79K", tier: 2, signal: "Pending" },
    { city: "Malibu", pop: "10K", tier: 3, signal: "Idle" },
  ],
  CO: [
    { city: "Denver", pop: "713K", tier: 1, signal: "Active" },
    { city: "Boulder", pop: "108K", tier: 1, signal: "Active" },
    { city: "Colorado Springs", pop: "478K", tier: 2, signal: "Pending" },
    { city: "Aspen", pop: "7K", tier: 3, signal: "Idle" },
  ],
  CT: [
    { city: "Stamford", pop: "135K", tier: 1, signal: "Active" },
    { city: "New Haven", pop: "134K", tier: 2, signal: "Pending" },
    { city: "Hartford", pop: "121K", tier: 2, signal: "Pending" },
    { city: "Greenwich", pop: "63K", tier: 1, signal: "Active" },
  ],
  DE: [
    { city: "Wilmington", pop: "70K", tier: 1, signal: "Active" },
    { city: "Dover", pop: "39K", tier: 2, signal: "Pending" },
    { city: "Rehoboth Beach", pop: "1K", tier: 3, signal: "Idle" },
  ],
  FL: [
    { city: "Miami", pop: "442K", tier: 1, signal: "Active" },
    { city: "Orlando", pop: "307K", tier: 1, signal: "Active" },
    { city: "Tampa", pop: "384K", tier: 1, signal: "Active" },
    { city: "Fort Lauderdale", pop: "182K", tier: 1, signal: "Active" },
    { city: "Jacksonville", pop: "949K", tier: 2, signal: "Pending" },
    { city: "Naples", pop: "19K", tier: 2, signal: "Pending" },
    { city: "Key West", pop: "25K", tier: 3, signal: "Idle" },
  ],
  GA: [
    { city: "Atlanta", pop: "499K", tier: 1, signal: "Active" },
    { city: "Savannah", pop: "147K", tier: 1, signal: "Active" },
    { city: "Augusta", pop: "202K", tier: 2, signal: "Pending" },
    { city: "Athens", pop: "127K", tier: 3, signal: "Idle" },
  ],
  HI: [
    { city: "Honolulu", pop: "350K", tier: 1, signal: "Active" },
    { city: "Maui", pop: "18K", tier: 2, signal: "Pending" },
    { city: "Kailua", pop: "38K", tier: 3, signal: "Idle" },
  ],
  ID: [
    { city: "Boise", pop: "236K", tier: 1, signal: "Active" },
    { city: "Meridian", pop: "129K", tier: 2, signal: "Pending" },
    { city: "Sun Valley", pop: "1K", tier: 3, signal: "Idle" },
  ],
  IL: [
    { city: "Chicago", pop: "2.7M", tier: 1, signal: "Active" },
    { city: "Naperville", pop: "149K", tier: 1, signal: "Active" },
    { city: "Springfield", pop: "114K", tier: 2, signal: "Pending" },
    { city: "Evanston", pop: "78K", tier: 2, signal: "Pending" },
  ],
  IN: [
    { city: "Indianapolis", pop: "888K", tier: 1, signal: "Active" },
    { city: "Fort Wayne", pop: "267K", tier: 2, signal: "Pending" },
    { city: "Bloomington", pop: "85K", tier: 3, signal: "Idle" },
  ],
  IA: [
    { city: "Des Moines", pop: "214K", tier: 1, signal: "Active" },
    { city: "Cedar Rapids", pop: "137K", tier: 2, signal: "Pending" },
    { city: "Iowa City", pop: "74K", tier: 3, signal: "Idle" },
  ],
  KS: [
    { city: "Wichita", pop: "397K", tier: 1, signal: "Active" },
    { city: "Kansas City", pop: "156K", tier: 2, signal: "Pending" },
    { city: "Topeka", pop: "126K", tier: 3, signal: "Idle" },
  ],
  KY: [
    { city: "Louisville", pop: "633K", tier: 1, signal: "Active" },
    { city: "Lexington", pop: "322K", tier: 2, signal: "Pending" },
    { city: "Bowling Green", pop: "72K", tier: 3, signal: "Idle" },
  ],
  LA: [
    { city: "New Orleans", pop: "383K", tier: 1, signal: "Active" },
    { city: "Baton Rouge", pop: "225K", tier: 2, signal: "Pending" },
    { city: "Shreveport", pop: "184K", tier: 3, signal: "Idle" },
  ],
  ME: [
    { city: "Portland", pop: "68K", tier: 1, signal: "Active" },
    { city: "Bar Harbor", pop: "5K", tier: 2, signal: "Pending" },
    { city: "Augusta", pop: "19K", tier: 3, signal: "Idle" },
  ],
  MD: [
    { city: "Baltimore", pop: "585K", tier: 1, signal: "Active" },
    { city: "Annapolis", pop: "39K", tier: 1, signal: "Active" },
    { city: "Bethesda", pop: "65K", tier: 2, signal: "Pending" },
    { city: "Rockville", pop: "71K", tier: 2, signal: "Pending" },
  ],
  MA: [
    { city: "Boston", pop: "675K", tier: 1, signal: "Active" },
    { city: "Cambridge", pop: "118K", tier: 1, signal: "Active" },
    { city: "Nantucket", pop: "14K", tier: 2, signal: "Pending" },
    { city: "Martha's Vineyard", pop: "17K", tier: 2, signal: "Pending" },
    { city: "Worcester", pop: "206K", tier: 3, signal: "Idle" },
  ],
  MI: [
    { city: "Detroit", pop: "639K", tier: 1, signal: "Active" },
    { city: "Ann Arbor", pop: "123K", tier: 1, signal: "Active" },
    { city: "Grand Rapids", pop: "198K", tier: 2, signal: "Pending" },
    { city: "Traverse City", pop: "15K", tier: 3, signal: "Idle" },
  ],
  MN: [
    { city: "Minneapolis", pop: "429K", tier: 1, signal: "Active" },
    { city: "St. Paul", pop: "311K", tier: 1, signal: "Active" },
    { city: "Duluth", pop: "92K", tier: 2, signal: "Pending" },
  ],
  MS: [
    { city: "Jackson", pop: "153K", tier: 1, signal: "Active" },
    { city: "Gulfport", pop: "71K", tier: 2, signal: "Pending" },
    { city: "Biloxi", pop: "49K", tier: 3, signal: "Idle" },
  ],
  MO: [
    { city: "St. Louis", pop: "301K", tier: 1, signal: "Active" },
    { city: "Kansas City", pop: "508K", tier: 1, signal: "Active" },
    { city: "Springfield", pop: "169K", tier: 2, signal: "Pending" },
  ],
  MT: [
    { city: "Missoula", pop: "73K", tier: 1, signal: "Active" },
    { city: "Bozeman", pop: "53K", tier: 1, signal: "Active" },
    { city: "Whitefish", pop: "7K", tier: 2, signal: "Pending" },
    { city: "Big Sky", pop: "3K", tier: 3, signal: "Idle" },
  ],
  NE: [
    { city: "Omaha", pop: "486K", tier: 1, signal: "Active" },
    { city: "Lincoln", pop: "291K", tier: 2, signal: "Pending" },
    { city: "Scottsbluff", pop: "15K", tier: 3, signal: "Idle" },
  ],
  NV: [
    { city: "Las Vegas", pop: "641K", tier: 1, signal: "Active" },
    { city: "Reno", pop: "264K", tier: 1, signal: "Active" },
    { city: "Henderson", pop: "317K", tier: 2, signal: "Pending" },
  ],
  NH: [
    { city: "Manchester", pop: "115K", tier: 1, signal: "Active" },
    { city: "Concord", pop: "44K", tier: 2, signal: "Pending" },
    { city: "Portsmouth", pop: "21K", tier: 2, signal: "Pending" },
  ],
  NJ: [
    { city: "Newark", pop: "311K", tier: 1, signal: "Active" },
    { city: "Princeton", pop: "31K", tier: 1, signal: "Active" },
    { city: "Hoboken", pop: "60K", tier: 1, signal: "Active" },
    { city: "Atlantic City", pop: "38K", tier: 2, signal: "Pending" },
    { city: "Asbury Park", pop: "16K", tier: 3, signal: "Idle" },
  ],
  NM: [
    { city: "Albuquerque", pop: "564K", tier: 1, signal: "Active" },
    { city: "Santa Fe", pop: "87K", tier: 2, signal: "Pending" },
    { city: "Taos", pop: "6K", tier: 3, signal: "Idle" },
  ],
  NY: [
    { city: "New York City", pop: "8.3M", tier: 1, signal: "Active" },
    { city: "Brooklyn", pop: "2.7M", tier: 1, signal: "Active" },
    { city: "Long Island", pop: "1.6M", tier: 1, signal: "Active" },
    { city: "Westchester", pop: "968K", tier: 1, signal: "Active" },
    { city: "The Hamptons", pop: "130K", tier: 1, signal: "Active" },
    { city: "Buffalo", pop: "278K", tier: 2, signal: "Pending" },
    { city: "Saratoga Springs", pop: "28K", tier: 2, signal: "Pending" },
    { city: "Hudson", pop: "6K", tier: 3, signal: "Idle" },
  ],
  NC: [
    { city: "Charlotte", pop: "874K", tier: 1, signal: "Active" },
    { city: "Raleigh", pop: "467K", tier: 1, signal: "Active" },
    { city: "Asheville", pop: "94K", tier: 1, signal: "Active" },
    { city: "Durham", pop: "283K", tier: 2, signal: "Pending" },
    { city: "Wilmington", pop: "123K", tier: 3, signal: "Idle" },
  ],
  ND: [
    { city: "Fargo", pop: "126K", tier: 1, signal: "Active" },
    { city: "Bismarck", pop: "73K", tier: 2, signal: "Pending" },
    { city: "Grand Forks", pop: "56K", tier: 3, signal: "Idle" },
  ],
  OH: [
    { city: "Columbus", pop: "905K", tier: 1, signal: "Active" },
    { city: "Cleveland", pop: "372K", tier: 1, signal: "Active" },
    { city: "Cincinnati", pop: "309K", tier: 1, signal: "Active" },
    { city: "Akron", pop: "190K", tier: 2, signal: "Pending" },
    { city: "Dayton", pop: "137K", tier: 2, signal: "Pending" },
    { city: "Toledo", pop: "270K", tier: 3, signal: "Idle" },
  ],
  OK: [
    { city: "Oklahoma City", pop: "681K", tier: 1, signal: "Active" },
    { city: "Tulsa", pop: "413K", tier: 2, signal: "Pending" },
    { city: "Norman", pop: "128K", tier: 3, signal: "Idle" },
  ],
  OR: [
    { city: "Portland", pop: "652K", tier: 1, signal: "Active" },
    { city: "Bend", pop: "102K", tier: 1, signal: "Active" },
    { city: "Eugene", pop: "176K", tier: 2, signal: "Pending" },
    { city: "Ashland", pop: "21K", tier: 3, signal: "Idle" },
  ],
  PA: [
    { city: "Philadelphia", pop: "1.6M", tier: 1, signal: "Active" },
    { city: "Pittsburgh", pop: "302K", tier: 1, signal: "Active" },
    { city: "Allentown", pop: "125K", tier: 2, signal: "Pending" },
    { city: "State College", pop: "42K", tier: 3, signal: "Idle" },
  ],
  RI: [
    { city: "Providence", pop: "190K", tier: 1, signal: "Active" },
    { city: "Newport", pop: "25K", tier: 1, signal: "Active" },
    { city: "Narragansett", pop: "16K", tier: 3, signal: "Idle" },
  ],
  SC: [
    { city: "Charleston", pop: "150K", tier: 1, signal: "Active" },
    { city: "Columbia", pop: "136K", tier: 2, signal: "Pending" },
    { city: "Myrtle Beach", pop: "35K", tier: 3, signal: "Idle" },
  ],
  SD: [
    { city: "Sioux Falls", pop: "192K", tier: 1, signal: "Active" },
    { city: "Rapid City", pop: "79K", tier: 2, signal: "Pending" },
    { city: "Deadwood", pop: "1K", tier: 3, signal: "Idle" },
  ],
  TN: [
    { city: "Nashville", pop: "689K", tier: 1, signal: "Active" },
    { city: "Memphis", pop: "633K", tier: 1, signal: "Active" },
    { city: "Knoxville", pop: "190K", tier: 2, signal: "Pending" },
    { city: "Chattanooga", pop: "184K", tier: 3, signal: "Idle" },
  ],
  TX: [
    { city: "Houston", pop: "2.3M", tier: 1, signal: "Active" },
    { city: "Austin", pop: "979K", tier: 1, signal: "Active" },
    { city: "Dallas", pop: "1.3M", tier: 1, signal: "Active" },
    { city: "San Antonio", pop: "1.5M", tier: 1, signal: "Active" },
    { city: "Fort Worth", pop: "918K", tier: 1, signal: "Active" },
    { city: "Marfa", pop: "1.7K", tier: 2, signal: "Pending" },
    { city: "El Paso", pop: "678K", tier: 2, signal: "Pending" },
    { city: "Galveston", pop: "50K", tier: 3, signal: "Idle" },
  ],
  UT: [
    { city: "Salt Lake City", pop: "200K", tier: 1, signal: "Active" },
    { city: "Park City", pop: "8K", tier: 1, signal: "Active" },
    { city: "Provo", pop: "115K", tier: 2, signal: "Pending" },
    { city: "Moab", pop: "5K", tier: 3, signal: "Idle" },
  ],
  VT: [
    { city: "Burlington", pop: "44K", tier: 1, signal: "Active" },
    { city: "Stowe", pop: "5K", tier: 2, signal: "Pending" },
    { city: "Woodstock", pop: "3K", tier: 3, signal: "Idle" },
  ],
  VA: [
    { city: "Richmond", pop: "226K", tier: 1, signal: "Active" },
    { city: "Virginia Beach", pop: "459K", tier: 1, signal: "Active" },
    { city: "Alexandria", pop: "159K", tier: 1, signal: "Active" },
    { city: "Charlottesville", pop: "46K", tier: 2, signal: "Pending" },
    { city: "Williamsburg", pop: "15K", tier: 3, signal: "Idle" },
  ],
  WA: [
    { city: "Seattle", pop: "737K", tier: 1, signal: "Active" },
    { city: "Bellevue", pop: "151K", tier: 1, signal: "Active" },
    { city: "Tacoma", pop: "219K", tier: 2, signal: "Pending" },
    { city: "Spokane", pop: "228K", tier: 3, signal: "Idle" },
  ],
  WV: [
    { city: "Charleston", pop: "46K", tier: 1, signal: "Active" },
    { city: "Morgantown", pop: "30K", tier: 2, signal: "Pending" },
    { city: "Lewisburg", pop: "4K", tier: 3, signal: "Idle" },
  ],
  WI: [
    { city: "Milwaukee", pop: "577K", tier: 1, signal: "Active" },
    { city: "Madison", pop: "259K", tier: 1, signal: "Active" },
    { city: "Green Bay", pop: "107K", tier: 2, signal: "Pending" },
    { city: "Lake Geneva", pop: "5K", tier: 3, signal: "Idle" },
  ],
  WY: [
    { city: "Jackson", pop: "11K", tier: 1, signal: "Active" },
    { city: "Cody", pop: "10K", tier: 2, signal: "Pending" },
    { city: "Jackson Hole", pop: "11K", tier: 1, signal: "Active" },
  ],
};

export function getCities(stateId: string) {
  return CITIES[stateId] ?? [];
}
